### ISSUE TITLE
Vester checklist

### ISSUE THREAD

**Issue by damip** [massalabs/coin-vester#9]
* [ ] in the frontend:
  * [ ] put the tutorial message on top just below the title (see below)
  * [ ] make the "send vested coins" part foldable, folded by default
  * [ ] in the claim part, if the wallet is not connected, put a message saying it and redirecting to station.massa.net
  * [ ] for the claim part, explicitly write "There are no active vesting sessions for your address [addr]" if there is nothing to display

Tutorial message:

```
This tool allows sending and receiving vested MAS tokens securely.
This app requires a compatible Massa wallet. We recommend https://station.massa.net .
The "Claim Received Funds" section displays the active vesting sessions targeting your wallet address.
For each session, the currently available amount that can be claimed is displayed as "Available to Claim (nMAS)".
In order to claim a certain amount from the available amount of a session, simply enter the amount you want to claim and press the green "Claim" button.
Note that in order to preserve precision and remove any ambiguity, all displayed amounts, as well as the amounts you are expected to input are in nano-MAS (nMAS).
This means for example that in order to claim 123.456 MAS  you should input 123456000000
```

**Comment by Thykof** [comment]
This is done and we improved it
